import { Inter } from 'next/font/google'
import './globals.css'
import CursorTrail from '@/components/CursorTrail'
import ScrollToTop from "@/components/ScrollToTop"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kumar Sumitt Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Move CursorTrail after children to ensure it's on top */}
        {children}
        <ScrollToTop />
        <CursorTrail />
        {/* SVG Filter for blob effect */}
        <svg style={{ position: 'absolute', width: 0, height: 0 }}>
          <defs>
            <filter id="goo">
              <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
              <feColorMatrix
                in="blur"
                mode="matrix"
                values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -8"
                result="goo"
              />
              <feBlend in="SourceGraphic" in2="goo" />
            </filter>
          </defs>
        </svg>
      </body>
    </html>
  )
}